kind: pipeline
type: docker
name: build-amd64

platform:
  arch: amd64

steps:

 - name: build
   image: node:12
   commands:
     - apt update && apt install -y build-essential git libsecret-1-dev libx11-dev libxkbfile-dev
     - if [ ! -n $DRONE_TAG ]; then yarn build 1.41.1 daily; else yarn build 1.41.1 $DRONE_TAG; fi
     - if [ ! -n $DRONE_TAG ]; then yarn binary 1.41.1 daily; else yarn binary 1.41.1 $DRONE_TAG; fi
     - if [ ! -n $DRONE_TAG ]; then yarn package 1.41.1 daily; else yarn package 1.41.1 $DRONE_TAG; fi

 - name: build-alpine
   image: node:12-alpine
   commands:
     - apk add libxkbfile-dev libsecret-dev build-base git
     - if [ ! -n $DRONE_TAG ]; then yarn build 1.41.1 daily; else yarn build 1.41.1 $DRONE_TAG; fi
     - if [ ! -n $DRONE_TAG ]; then yarn binary 1.41.1 daily; else yarn binary 1.41.1 $DRONE_TAG; fi
     - if [ ! -n $DRONE_TAG ]; then yarn package 1.41.1 daily; else yarn package 1.41.1 $DRONE_TAG; fi

 - name: publish
   image: debian
   commands:
     - apt-get update && apt-get install -y wget
     - wget -qO -  https://github.com/tcnksm/ghr/releases/download/v0.12.0/ghr_v0.12.0_linux_amd64.tar.gz | tar -xvz
     - chmod -R 777 ghr_v0.12.0_linux_amd64/*
     - ./ghr_v0.12.0_linux_amd64/ghr "$DRONE_TAG" ./release/
   environment:
    GITHUB_TOKEN:
      from_secret: gh-token
   when:
    event: tag

---
kind: pipeline
type: docker
name: build-arm64

platform:
  arch: arm64

steps:

 - name: build
   image: node:12
   commands:
     - apt update && apt install -y build-essential git libsecret-1-dev libx11-dev libxkbfile-dev
     - if [ ! -n $DRONE_TAG ]; then yarn build 1.41.1 daily; else yarn build 1.41.1 $DRONE_TAG; fi
     - if [ ! -n $DRONE_TAG ]; then yarn binary 1.41.1 daily; else yarn binary 1.41.1 $DRONE_TAG; fi
     - if [ ! -n $DRONE_TAG ]; then yarn package 1.41.1 daily; else yarn package 1.41.1 $DRONE_TAG; fi

 - name: build-alpine
   image: node:12-alpine
   commands:
     - apk add libxkbfile-dev libsecret-dev build-base git
     - if [ ! -n $DRONE_TAG ]; then yarn build 1.41.1 daily; else yarn build 1.41.1 $DRONE_TAG; fi
     - if [ ! -n $DRONE_TAG ]; then yarn binary 1.41.1 daily; else yarn binary 1.41.1 $DRONE_TAG; fi
     - if [ ! -n $DRONE_TAG ]; then yarn package 1.41.1 daily; else yarn package 1.41.1 $DRONE_TAG; fi

 - name: publish
   image: debian
   commands:
     - apt-get update && apt-get install -y wget
     - wget -qO -  https://github.com/tcnksm/ghr/releases/download/v0.12.0/ghr_v0.12.0_linux_amd64.tar.gz | tar -xvz
     - chmod -R 777 ghr_v0.12.0_linux_amd64/*
     - ./ghr_v0.12.0_linux_amd64/ghr "$DRONE_TAG" ./release/
   environment:
    GITHUB_TOKEN:
      from_secret: gh-token
   when:
    event: tag

---
kind: pipeline
type: docker
name: build-arm

platform:
  arch: arm

steps:

 - name: build
   image: node:12
   commands:
     - apt update && apt install -y build-essential git libsecret-1-dev libx11-dev libxkbfile-dev
     - yarn
     - if [ ! -n $DRONE_TAG ]; then yarn build 1.41.1 daily; else yarn build 1.41.1 $DRONE_TAG; fi
     - if [ ! -n $DRONE_TAG ]; then yarn binary 1.41.1 daily; else yarn binary 1.41.1 $DRONE_TAG; fi

 - name: build-alpine
   image: node:12-alpine
   commands:
     - apk add libxkbfile-dev libsecret-dev build-base git
     - if [ ! -n $DRONE_TAG ]; then yarn build 1.41.1 daily; else yarn build 1.41.1 $DRONE_TAG; fi
     - if [ ! -n $DRONE_TAG ]; then yarn binary 1.41.1 daily; else yarn binary 1.41.1 $DRONE_TAG; fi
     - if [ ! -n $DRONE_TAG ]; then yarn package 1.41.1 daily; else yarn package 1.41.1 $DRONE_TAG; fi

 - name: publish
   image: debian
   commands:
     - apt-get update && apt-get install -y wget
     - wget -qO -  https://github.com/tcnksm/ghr/releases/download/v0.12.0/ghr_v0.12.0_linux_amd64.tar.gz | tar -xvz
     - chmod -R 777 ghr_v0.12.0_linux_amd64/*
     - ./ghr_v0.12.0_linux_amd64/ghr "$DRONE_TAG" ./release/
   environment:
    GITHUB_TOKEN:
      from_secret: gh-token
   when:
    event: tag
